In [9]:
import sqlite3
import pandas as pd
from pathlib import Path

# Path to your merged CSV
base = Path("C:/Users/HP Omen 15/Documents/[BS Economics]/RESUME/CSC_job_listings")
csv_path = base / "MergedData.csv"

# Load CSV into pandas
df = pd.read_csv(csv_path)

# Connect to SQLite (creates a local DB file)
conn = sqlite3.connect("csc_job_listings.db")

# Write DataFrame to SQL table
df.to_sql("csc_job_listings", conn, if_exists="replace", index=False)

46700

In [10]:
# Example SQL query
query = "SELECT * FROM csc_job_listings;"
results = pd.read_sql_query(query, conn)

results

,Agency,Region,Position Title,Plantilla Item No.,Posting Date,Closing Date
0,PALAWAN STATE UNIVERSITY,Region IV,Administrative Officer II (Administrative Offi...,PSCB-ADOF2-151-2025,13 Nov 25,24 Nov 25
1,PALAWAN STATE UNIVERSITY,Region IV,Administrative Assistant II \n(Clerk IV),PSCB-ADAS2-88-2025,13 Nov 25,24 Nov 25
2,PALAWAN STATE UNIVERSITY,Region IV,Administrative Assistant II \n(Clerk IV),PSCB-ADAS2-89-2025,13 Nov 25,24 Nov 25
3,PALAWAN STATE UNIVERSITY,Region IV,Administrative Assistant II \n(Clerk IV),PSCB-ADAS2-90-2025,13 Nov 25,24 Nov 25
4,PALAWAN STATE UNIVERSITY,Region IV,Administrative Assistant II \n(Clerk IV),PSCB-ADAS2-91-2025,13 Nov 25,24 Nov 25
...,...,...,...,...,...,...
46695,CITY GOVERNMENT OF BACOOR,Region IV,Mechanic III,926,27 Oct 25,11 Nov 25
46696,CITY GOVERNMENT OF BACOOR,Region IV,Carpenter I,924; 925,27 Oct 25,11 Nov 25
46697,CITY GOVERNMENT OF BACOOR,Region IV,Plumber I,922; 923,27 Oct 25,11 Nov 25
46698,CITY GOVERNMENT OF BACOOR,Region IV,Welder I,929; 930,27 Oct 25,11 Nov 25
46699,CITY GOVERNMENT OF BACOOR,Region IV,Painter I,920; 921,27 Oct 25,11 Nov 25

In [14]:
query = "PRAGMA table_info(csc_job_listings);"
pd.read_sql_query(query, conn)

   cid                name  type  notnull dflt_value  pk
0    0              Agency  TEXT        0       None   0
1    1              Region  TEXT        0       None   0
2    2      Position Title  TEXT        0       None   0
3    3  Plantilla Item No.  TEXT        0       None   0
4    4        Posting Date  TEXT        0       None   0
5    5        Closing Date  TEXT        0       None   0

In [17]:
query = """
SELECT DISTINCT "Position Title"
FROM csc_job_listings
ORDER BY "Position Title"
"""
# Run query and store results in DataFrame
df = pd.read_sql_query(query, conn)
df

                                         Position Title
0     (1) Engineer II\n(Coterminous with the Build, ...
1                       (2) Revenue Collection Clerk II
2     (Administrative Assistant)                    ...
3     (Administrative Officer IV)                   ...
4     (Bookbinder II)                               ...
...                                                 ...
4873                                  Zoning Officer II
4874                                 Zoning Officer III
4875                                  Zoning Officer IV
4876                                        Zoologist V
4877                         olice Corporal (160 quota)

[4878 rows x 1 columns]

In [ ]:
# Export DataFrame to CSV
output_path = "unique_position_titles.csv"
df.to_csv(output_path, index=False)

print(f"Results saved to {output_path}")

Results saved to unique_position_titles.csv

In [18]:
query = """
SELECT DISTINCT Agency
FROM csc_job_listings
ORDER BY Agency
"""
# Run query and store results in DataFrame
df = pd.read_sql_query(query, conn)
df

                                                 Agency
0                                       (CGO PASAY NCR)
1          (National Commission for Culture & the Arts)
2                      (Provincial Government of Leyte)
3       ABRA STATE INSTITUTE OF SCIENCES AND TECHNOLOGY
4                ADELA SERRA TY MEMORIAL MEDICAL CENTER
...                                                 ...
1383                     WESTERN VISAYAS MEDICAL CENTER
1384    WESTERN VISAYAS SANITARIUM AND GENERAL HOSPITAL
1385                     Western Philippines University
1386                      ZAMBOANGA CITY WATER DISTRICT
1387  ZAMBOANGA STATE COLLEGE OF MARINE SCIENCES AND...

[1388 rows x 1 columns]

In [21]:
query = """
SELECT DISTINCT "Position Title"
FROM csc_job_listings
WHERE Region IN ('Region VII', 'Region VIII')
ORDER BY "Position Title";
"""
# Run query and store results in DataFrame
df = pd.read_sql_query(query, conn)
df

                               Position Title
0                 * * * Nothing Follows * * *
1                               ACCOUNTANT II
2                               ACCOUNTANT IV
3           ADMINISTRATIVE AIDE I (LABORER I)
4    ADMINISTRATIVE AIDE I (UTILITY WORKER I)
..                                        ...
865                                Watchman I
866          Water/Sewerage Maintenance Man C
867               Waterworks Superintendent I
868                     Waterworks Supervisor
869               Youth Development Officer I

[870 rows x 1 columns]

In [22]:
# Export DataFrame to CSV
output_path = "UniquePositionsR7R8.csv"
df.to_csv(output_path, index=False)

print(f"Results saved to {output_path}")

Results saved to UniquePositionsR7R8.csv

In [ ]:

print(results)

# Close connection
conn.close()